### ISSUE TITLE
How do I turn the .c and .h files into a .tns file?

### ISSUE THREAD

**Issue by TheRealSailent** [Vogtinator/gpsp#15]
Sorry I have absolutely no clue how to do this :( Could you add the tns files to the repository? thanks so much

**Comment by Vogtinator** [comment]
You'd have to set up the SDK and compile it yourself, which is quite an effort just for this.

I uploaded a recent build of gpsp here: https://github.com/ndless-nspire/Ndless/issues/256#issuecomment-731383777
