### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by phyllocrania** [Vogtinator/gpsp#2]
I have installed gpSP on my Ndlessed nspire (OS 4.5, rev. AB), however my mario 3 rom sometimes reboots after beating the final level on a world. Is this normal? (It does show activating compatibility mode)

Installed from: https://tiplanet.org/forum/archives_voir.php?id=6622

**Comment by Vogtinator** [comment]
Does the game or the calculator crash?

**Comment by phyllocrania** [comment]
I fixed the glitch, it was a ROM issue.  However, a gpSP update for rev W+ calculators would be helpful in terms of speed? Is such a thing possible?

**Comment by Vogtinator** [comment]
> However, a gpSP update for rev W+ calculators would be helpful in terms of speed? Is such a thing possible?

Yes, it should be possible. The issue is that the problem is not understood yet.
