### ISSUE TITLE
Makefile doesn't work on mac

### ISSUE THREAD

**Issue by kelvinnkat** [Vogtinator/gpsp#4]
When I try to compile using makefile, it gives me the following message:
Last login: Thu Sep 13 12:31:47 on ttys000
90301658$ /Users/90301658/Documents/final\ apcsp/gpsp-master/nspire/Makefile ; exit;
clang: error: no such file or directory: '='
clang: error: no such file or directory: 'nspire-gcc'
clang: error: no input files
ld: file not found: =
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 7: GENZEHN: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 8: VPATH: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 9: GCCFLAGS: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 10: LDFLAGS: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 11: ZEHNFLAGS: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 12: OBJS: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 15: DISTDIR: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 16: DISTDIR: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 16: vpath: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 18: all:: command not found
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 20: fg: no job control
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 21: syntax error near unexpected token `newline'
/Users/90301658/Documents/final apcsp/gpsp-master/nspire/Makefile: line 21: `	$(GCC) $(GCCFLAGS) -c $<'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by adriweb** [comment]
Looks like the toolchain wasn’t installed properly or at all? Moreover, about spaces in your paths.

**Comment by Vogtinator** [comment]
`Makefile` is not a shell script. Run `make`.

**Comment by kelvinnkat** [comment]
How do I run make?

**Comment by kelvinnkat** [comment]
Also a compiled version would be nice
