### ISSUE TITLE
Gpsp emulator on my nspire cx runs slower than some other nspires in an old yt video

### ISSUE THREAD

**Issue by anoopsk** [Vogtinator/gpsp#5]
Are there any solutions to this?

**Comment by Vogtinator** [comment]
Which HW rev? Please try https://github.com/ndless-nspire/Ndless/pull/202#issuecomment-594753861

**Comment by anoopsk** [comment]
HW-AE
I'll try the resources file

**Comment by anoopsk** [comment]
Thank you, I cannot express how grateful I am. The speed matches the speed of those calculators in the video.

**Comment by anoopsk** [comment]
Also, the experience would be better if you add a low brightness mode to the emulator as a feature, gbc4nspire has this feature.

**Comment by adriweb** [comment]
By the way, what are the letters/numbers before the AE revision on the back of your calc? Those indicate factory and date

**Comment by anoopsk** [comment]
It is N-1018AE - November 2018

**Comment by Vogtinator** [comment]
Thanks for testing! I'll close it as dup.
