### ISSUE TITLE
When I try 16MB games such as Zelda Minish cap, or mario superstar saga, the screen would become white and freeze. I would always have to reset the calculator.

### ISSUE THREAD

**Issue by anoopsk** [Vogtinator/gpsp#6]
Btw I'm using that updated resources file that you recommended me.

**Comment by anoopsk** [comment]
Can you please fix the issue

**Comment by Vogtinator** [comment]
Just tried Minish Cap, worked fine here. Maybe just try waiting a bit?

**Comment by anoopsk** [comment]
Just tried the Minish Cap again, the problem still persists. Has been stuck on white screen infinitely. I had to reset the calculator after 20 mins of waiting.

**Comment by anoopsk** [comment]
![IMG_20200823_192746](https://user-images.githubusercontent.com/65862092/90985905-cc9d8b80-e576-11ea-950a-caf512b90710.jpg)

**Comment by adriweb** [comment]
What's the datecode of your calculator ? (The few characters on the back of the calc, to the the right of the serial number. It may look like P-1234X)

**Comment by anoopsk** [comment]
N-1018AE

**Comment by anoopsk** [comment]
I even did a full reset of my calculator and transferred the Minish cap and other files, but the white screen still appears

**Comment by anoopsk** [comment]
These games now work on my CX II
