### ISSUE TITLE
Compatibility with ndless 5.2

### ISSUE THREAD

**Issue by FerdinandoPH** [Vogtinator/gpsp#7]
I have a Ti nspire cx ii cas t with ndless 5.2 . When I try to load the app, the compatibility mode screen pops up and then the calculator crashes. I don't know if this is because of ndless or because of the app

**Comment by adriweb** [comment]
Hmm on my CX II this build works fine for me (no crash): https://tiplanet.org/forum/archives_voir.php?id=6622 (green download button at the top). How about that one for you?

**Comment by FerdinandoPH** [comment]
Same problem. I think that the problem may be my revision (n-0320AK)

**Comment by chenxi050402** [comment]
Spam the enter button when opening.

**Comment by chenxi050402** [comment]
And some games such as Super Mario Bros. and Grand Theft Auto Advance will crash

**Comment by FerdinandoPH** [comment]
It worked with mario kart super circuit for me

**Comment by FerdinandoPH** [comment]
This is a problem of Ndless with N-0320AK models
https://github.com/ndless-nspire/Ndless/issues/236
